spring:
  datasource:
    url: ${SPRING_PG_DATASOURCE_URL}
    username: ${SPRING_PG_DATASOURCE_USER}
    password: ${SPRING_PG_DATASOURCE_PASSWORD}
    maxActive: 6
    maxIdle: 6
    minIdle: 5
    initialSize: 5

logging:
  level:
    org.springframework: DEBUG
    com.dell: INFO
